FROM arm32v7/python:3.9-alpine@sha256:7c62c7fb94b48a52b931f17b46c2451923fefa9ea759489b02b1a4b8441b5852

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="ansible-later"
LABEL org.opencontainers.image.url="https://ansible-later.geekdocs.de/"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/ansible-later"
LABEL org.opencontainers.image.documentation="https://ansible-later.geekdocs.de/"

ENV PY_COLORS=1
ENV CARGO_NET_GIT_FETCH_WITH_CLI=true

ADD dist/ansible_later-*.whl /

RUN apk --update add --virtual .build-deps build-base libffi-dev musl-dev libressl-dev python3-dev cargo && \
    apk --update add git && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir $(find / -name "ansible_later-*.whl")[ansible] && \
    apk del .build-deps && \
    rm -f ansible_later-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/ansible-later"]
