---
baseURL: https://ansible-later.geekdocs.de/
title: ansible-later
theme: hugo-geekdoc
pygmentsUseClasses: true
pygmentsCodeFences: true

# Geekdoc configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

params:
  description: >
    ansible-later is a fast and extensible best practice scanner and linting tool for Ansible resources
    to enforce a coding or best practice guideline.
  images:
    - "socialmedia2.png"

  geekdocMenuBundle: true
  geekdocToC: 3

  geekdocRepo: https://github.com/thegeeklab/ansible-later
  geekdocEditPath: edit/main/docs

  geekdocDateFormat: "Jan 2, 2006"
  geekdocSearch: true

  geekdocLegalNotice: https://thegeeklab.de/legal-notice/#contact-information
  geekdocPrivacyPolicy: https://thegeeklab.de/legal-notice/#privacy-policy
