---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

matrix:
  PYTHON_VERSION:
    - "3.9"
    - "3.10"
    - "3.11"
    - "3.12"

steps:
  pytest:
    image: docker.io/library/python:${PYTHON_VERSION}
    commands:
      - git fetch --depth=2147483647
      - pip install poetry poetry-dynamic-versioning -qq
      - poetry install -E ansible-core
      - poetry run pytest --cov-append
      - poetry version
      - poetry run ${CI_REPO_NAME} --help
    environment:
      PY_COLORS: "1"
